version: "3.9"

services:
  backend:
    build:
      context: ./LiveTradeX-Backend-main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - maven-repo:/root/.m2  # ✅ speeds up Maven build

  frontend:
    build:
      context: ./LiveTradeX_FrontEnd-main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://backend:8080
    depends_on:
      - backend

volumes:
  maven-repo:
