version: "3.9"

services:
  backend:
    build:
      context: ./LiveTradeX-Backend-main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .                # 👈 this is where Dockerfile and package.json are
      dockerfile: Dockerfile    # 👈 fixed: no longer pointing to a non-existent path
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://backend:8080
    depends_on:
      - backend
