services:
  backend:
    build:
      context: ./LiveTradeX-Backend-main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./LiveTradeX_FrontEnd-main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://backend:8080
    depends_on:
      - backend
